// Comment User
GET http://localhost:8050/comment

###
GET http://localhost:8050/comment/637b322f9331ae5f44b4c1ab

###
POST http://localhost:8050/comment
Content-Type: application/json

{
    "name": "Dony",
    "comment": "hooh tenan hooh tenan"
}

###
PATCH http://localhost:8050/comment/637b322f9331ae5f44b4c1ab
Content-Type: application/json

{
    "name": "Dony",
    "comment": "Amimir Amimir Amimir"
}

###
DELETE http://localhost:8050/comment/637b322f9331ae5f44b4c1ab


###
//User
GET http://localhost:8050/user

###
POST http://localhost:8050/register
Content-Type: application/json

{
    "name": "yowyow",
    "email": "yowyow@gmail.com",
    "password": "12345678",
    "re_password": "12345678"
}

###
POST http://localhost:8050/login
Content-Type: application/json

{
    "email": "yowyow@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:8050/thread
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inlvd3lvd0BnbWFpbC5jb20iLCJpZCI6IjYzN2I4MTNmNmNiNWU4MDQyNzUyODljMiIsImlhdCI6MTY3MDE2ODU2OX0.qFCrl_o2u1xu46AnVqTfovhr00G9f70jlWmTTPCdjdE